-- TODO: Write a query that uses window functions on game_details 
-- to find out the following:
    -- What is the most games a team has won in a 90 game stretch?
    -- How many games in a row did LeBron James score over 10 points a game?